deploy: use the artifact's build version
Otherwise, in the case of two people deploying HC and PC concurrently,
you might wind up deploying a version to the wrong place.  In
particular:

version counter is 0.8.21
HC packages 0.8.22
PC bumps version number to 0.8.22
HC deploys to 0.8.23 (but all the packages contain version 0.8.22)
???

This way, we only read the version from a remote location once at
package-time, and keep that version number until we bless it by
deploying it publicly.

Change-Id: I67bae843098aa38c1230bd5e66f44c01e5ccc446

diff --git a/tools/build/deploy b/tools/build/deploy
--- a/tools/build/deploy
+++ b/tools/build/deploy
@@ -25,6 +25,19 @@ fi
 # single-quoted - we want $HOME expanded serverside
 DEPLOY_LOCKFILE='$HOME/deploy.lock'
 
+# The version file should have been produced by the packaging scripts.
+VERSION_FILE="$PACKAGE_DIR/current.ver"
+if [[ ! -r "$VERSION_FILE" ]]; then
+    echo "Expected to find a version file at $VERSION_FILE but I couldn't read the version number"
+    exit $ERRBADVERSION
+fi
+RELEASE_VERSION=$(cat "$VERSION_FILE" | cut -d = -f 2)
+# Check that the version string has the right format.
+if [[ ! $RELEASE_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+    echo "Expected version string matching <major>.<minor>.<build>, got '$RELEASE_VERSION'"
+    exit $ERRBADVERSION
+fi
+
 function lock_release_server() {
     echo "establishing deploy lock..."
     kssh $RELEASE_SERVER_LOGIN $RELEASE_SERVER_SHELL << ENDCMDS
@@ -121,7 +134,6 @@ if is_public ; then
     echo
 fi
 
-compute_next_release_version
 echo '+--------------------------'
 echo '| ' $RELEASE_VERSION $MODE
 echo '+--------------------------'
