Fix a bug in build failure detection.
Change-Id: I81c2ba9c5eda070394875c58fe1a8b895e2b7510

diff --git a/tools/build/make_client_installers b/tools/build/make_client_installers
--- a/tools/build/make_client_installers
+++ b/tools/build/make_client_installers
@@ -390,9 +390,15 @@ function make_installers() {
         JOBS="$JOBS $!"
     fi
 
+    if [ "$JOBS" == "" ] ; then
+        echo "The caller did not request to make any client installers!"
+        echo "This is likely a bug. Abort!"
+        exit 1
+    fi
+
     # Check that all the background tasks completed successfully
     FAIL=0
-    for JOB in "$JOBS" ; do
+    for JOB in $JOBS ; do
         wait $JOB || let "FAIL+=1"
     done
 
