new labeling system using ant property -Dlabeling_class:
Usage: ant <target> -Dlabeling_class=<a_class_name_in_com.aerofs.labeling.impl>

For example: ant deploy_client -Dlabeling_class=AeroFSMultiuser

See build.xml and generate_labeling for detail.

Other changes:
o move L from com.aerofs.lib to com.aerofs.labeling
o avoid the protoc ant target to delete gen directory
o have make_release_resources verify paths before removing them from aerofs.jar

Change-Id: Iec89b2992bc296002c5f9749eaeeb71807385032

diff --git a/tools/build/make_release_resources b/tools/build/make_release_resources
--- a/tools/build/make_release_resources
+++ b/tools/build/make_release_resources
@@ -104,6 +104,8 @@ function copy_java_class_files() {
     cp -Rf "${BUILD_OUTPUT_DIR}/bin"/* "$local_BIN"
 
     # remove unnecessary files (bin/com/aerofs/downloader will be moved away later)
+    # TODO (WW) make sure files to be removed are at correct locations. See the
+    # labeling process code for an example.
     find "${local_BIN}/" -name .DS_Store | xargs rm -f
 
     if [ "$MODE" == "PROD" ]; then
@@ -111,8 +113,14 @@ function copy_java_class_files() {
         rm -rf "${local_BIN}/com/aerofs/sak"
     fi
 
-    # Remove Comcast labelling
-    rm -rf "${local_BIN}/com/aerofs/l/CC.class"
+    # Remove unused labelling classes. See comments in the L class
+    # We first make sure we are removing the correct package.
+    local local_LABELING_IMPL="${local_BIN}/com/aerofs/labeling/impl"
+    if [ ! -f "${local_LABELING_IMPL}/AeroFSSingleuser.class" ]; then
+        echo "error: missing labeling package ${local_LABELING_IMPL}"
+        exit 1
+    fi
+    rm -rf "${local_LABELING_IMPL}"
 }
 
 ######################################################################
