Fix code signing on CI, use same code sign function in all cases
Change-Id: I1a10575381f8244bc3635979863e0ec6ffd464e5

diff --git a/tools/build/sign b/tools/build/sign
--- a/tools/build/sign
+++ b/tools/build/sign
@@ -20,11 +20,7 @@ function sign_exe() {
 
     CODESIGNING_PASSWORD=$(cat $CODESIGNING_PASSWORD_FILE)
     export PASSPHRASE="$CODESIGNING_PASSWORD"
-
-    if [[ -r "$CERT_FILE" && -r "$KEY_FILE" ]] ; then
-        echo >&2 "Can't find cert/key at $CERT_FILE and $KEY_FILE - do you need to mount a volume?"
-        exit 1
-    fi
+    [[ -r "$CERT_FILE" && -r "$KEY_FILE" ]] || (echo >&2 "Can't find cert/key at $CERT_FILE and $KEY_FILE - do you need to mount a volume?" && exit 1)
 
     printenv PASSPHRASE | signcode -spc "$CERT_FILE" -v "$KEY_FILE" \
         -a sha1 -$ commercial -t http://timestamp.verisign.com/scripts/timestamp.dll \
