OSX shellext: check for codesigning failure
Change-Id: I72466d015a100cb5ce8d6389fd8ea9eb87a8b824

diff --git a/src/shellext/osx_finder/tools/make-release b/src/shellext/osx_finder/tools/make-release
--- a/src/shellext/osx_finder/tools/make-release
+++ b/src/shellext/osx_finder/tools/make-release
@@ -1,4 +1,6 @@
 #!/bin/bash
+set -e
+
 thisdir=$(dirname $0)
 
 rm -rf $thisdir/../build/*
@@ -22,6 +24,10 @@ fi
 
 echo "Signing code..."
 codesign -f -s "Air Computing, Inc." $thisdir/../build/Library/ScriptingAdditions/AeroFSFinderExtension.osax
+if [ $? -ne 0 ] ; then
+    echo "Codesigning failed.  Do you have the keys installed in your keychain?"
+    exit 3
+fi
 
 echo "Moving to resource/client..."
 rm -rf $thisdir/../../../../resource/client/osx/AeroFSFinderExtension.osax
