server_sanity_check: use internal CA for SP url
We switched SP to run behind an AeroFS CA certificate.
We need to update the sanity check to match.
We can also improve on the error messages to see what the probes
returned when they fail.

Change-Id: I52a18439adf3326ad33399dba8532f1c1f68a271

diff --git a/puppetmaster/modules/puppet/files/server_sanity_check b/puppetmaster/modules/puppet/files/server_sanity_check
--- a/puppetmaster/modules/puppet/files/server_sanity_check
+++ b/puppetmaster/modules/puppet/files/server_sanity_check
@@ -6,8 +6,20 @@ url()
 {
     echo "Verifying $1"
     wget --timeout=10 --no-cache -q -O /dev/null $1
-    if [ $? != 0 ]; then
-        echo "Failure with url: $1"
+    CODE=$?
+    if [ $CODE != 0 ]; then
+        echo "Failure with url: $1 - wget returned $CODE"
+        SUCCESS=FALSE
+    fi
+}
+
+url-internal-ssl()
+{
+    echo "Verifying $1"
+    wget --ca-certificate=/etc/ssl/certs/AeroFS_CA.pem --timeout=10 --no-cache -q -O /dev/null $1
+    CODE=$?
+    if [ $CODE != 0 ]; then
+        echo "Failure with url: $1 - wget returned $CODE"
         SUCCESS=FALSE
     fi
 }
@@ -16,8 +28,9 @@ port()
 {
     echo "Verifying port $2 on $1"
     nc -z $1 $2 > /dev/null
-    if [ $? != 0 ]; then
-        echo "Failure with port $2 on $1"
+    CODE=$?
+    if [ $CODE != 0 ]; then
+        echo "Failure with port $2 on $1 - nc returned $CODE"
         SUCCESS=FALSE
     fi
 }
@@ -27,7 +40,7 @@ port x.aerofs.com 443
 port zephyr.aerofs.com 443
 url https://aerofs.com/login
 url https://sv.aerofs.com/sv_beta/sv
-url https://sp.aerofs.com/sp
+url-internal-ssl https://sp.aerofs.com/sp
 url https://sss.aerofs.com/syncstat
 
 if [ $SUCCESS == TRUE ]; then
