Syncdet tests weren't workign in local prod. I believe this solves.
One important consequence of this change is we would no longer support changing
the config_url in config.yaml.

diff --git a/tools/populate/populate b/tools/populate/populate
--- a/tools/populate/populate
+++ b/tools/populate/populate
@@ -75,13 +75,16 @@ function create_max_version_file() {
 function create_site_properties_file() {
     if [[ "$MODE" == 'ENTERPRISE' ]]
     then
-        if [ "$(nc -z persistent.syncfs.com 443)x" = "x" ]
+        set +e
+        wget -qO- --no-check-certificate https://persistent.syncfs.com/ | grep config.loader > "$APPROOT"/site-config.properties
+
+        if [[ $? -ne 0 ]]
         then
-            echo "Local prod configuration service not available."
+            echo "ERROR: Local prod configuration service not available."
             exit 1
         fi
 
-        wget -qO- --no-check-certificate https://persistent.syncfs.com/ | grep config.loader > "$APPROOT"/site-config.properties
+        set -e
     fi
 }
 
