OSUtil: fix Linux architecture detection
Unlike almost every other heuristic we've tried in the past, we can
pretty much rely on the executable's ELF header being valid and an
accurate representation of what architecture we're running on.

This conveniently brings Java's architecture detection into line with
the one that's used by the copier/launcher scripts, which have been
using trustworthy system invariants for quite some time now, with nary a
problem.

Change-Id: I22f1ac4154324bcc63007931b8be9625b06919fd

diff --git a/tools/populate/run b/tools/populate/run
--- a/tools/populate/run
+++ b/tools/populate/run
@@ -24,15 +24,27 @@ elif [ $OS == osx ]; then
     VMARGS="$VMARGS -XstartOnFirstThread"
     export DYLD_LIBRARY_PATH=$PPWD:$DYLD_LIBRARY_PATH
 elif [ x`echo $OS | grep linux` != x ]; then
+    # Architecture detection without dependencies beyond coreutils.
+    # ELF files start out "\x7fELF", and the following byte is
+    #   0x01 for 32-bit and
+    #   0x02 for 64-bit.
+    CURRENT_EXE_HEAD=$(head -c 5 /proc/self/exe )
+    case "$CURRENT_EXE_HEAD" in
+        "$(printf '\x7fELF\x01')")
+            # 32-bit ELF
+            JRE_LIB_ARCH=i386
+            ;;
+        "$(printf '\x7fELF\x02')")
+            # 64-bit ELF
+            JRE_LIB_ARCH=amd64
+            ;;
+        *)
+            echo "I don't recognize your userspace executable format, so I can't launch."
+            echo "Sorry about that."
+            exit 1
+    esac
     # We need to set the LD_LIBRARY_PATH to include the JRE directories so that
     # aerofsd will successfully launch
-    if [ x"$(file $(readlink -f /bin/ls) | grep 64)" != x ]; then
-        ARCH=64
-        JRE_LIB_ARCH=amd64
-    else
-        ARCH=32
-        JRE_LIB_ARCH=i386
-    fi
     JRE_BASE="$(dirname $(dirname $(readlink -f $(which java))))"
     # Oracle ships two "java" executables in the JDK package - one in the
     # jre/bin/ folder, and the other just in the bin/ folder.  This finds the
