Puppet module for the certificate authority.
Change-Id: Idfe93e0035a8283fea32d9128bf0e4b1bd604656

diff --git a/tools/puppet/deploy b/tools/puppet/deploy
--- a/tools/puppet/deploy
+++ b/tools/puppet/deploy
@@ -2,16 +2,22 @@
 
 set -e -u
 
-if [ $# -gt 1 ]; then
+usage()
+{
     echo "usage: $0 <puppetmaster>"
     echo "example: $0 puppet.arrowfs.org"
-    exit 2
+    exit $1
+}
+
+if [ $# -ne 1 ]; then
+    usage 2
 fi
 
 PUPPET_MASTER=${1:-}
+
 if [ x"$PUPPET_MASTER" == x ]; then
-    echo "puppetmaster server address is required"
-    exit 3
+    echo "puppetmaster server address is required."
+    usage 3
 fi
 
 # Get the directory this script is in no matter where it's called from
