Packaging for AeroFSMultiuser.
The general idea is I split up the deploy script into build and deploy.
Two builds are run in different modes. This creates the different
binaries. The binaries are then loaded onto s3 in the deploy step. The
deploy step also runs safetynet.

Modes are facilitated using the labeling classes. Installer names are
pulled from labeling as well, making build.xml very clean (yay).

For now we use the same proguard map file for both multi user and single
user. We can fix this later.

Also TODO in a different commit: AeroFS.app, AeroFS.exe and its parent
folder name, and ~/.aerofs-bin and /usr/share/bin/aerofs* scripts, should
all be changed.

Change-Id: Ieda52e7732f7cc232d2ecb46ed40e3d41352b589

diff --git a/tools/build/include/common b/tools/build/include/common
--- a/tools/build/include/common
+++ b/tools/build/include/common
@@ -96,10 +96,7 @@ readonly RELEASE_FILES_DIR="/home/release-${LOWERCASE_MODE}"
 readonly RELEASE_UNPACK_DIR="${RELEASE_FILES_DIR}/unpack"
 readonly INSTALLERS_DOWNLOAD_DIR="/data/${LOWERCASE_MODE}-downloads"
 readonly RELEASE_SERVER_VERSION_FILE="current.ver"
-
 readonly RELEASE_NSIS_DIR="${RELEASE_FILES_DIR}/win_installer"
-readonly WINDOWS_PATCHER_DIR="${RELEASE_NSIS_DIR}/patcher"
-readonly WINDOWS_PACKAGER_DIR="${RELEASE_NSIS_DIR}/packager"
 
 ###############################################################################
 #
@@ -149,6 +146,39 @@ function current_release_version() {
 
 ###############################################################################
 #
+# Checks the current active version on S3 and computes the next logical version.
+#
+###############################################################################
+function compute_next_release_version() {
+    local local_CURRENT_RELEASE_VERSION="$( current_release_version $RELEASE_VERSION_URL )"
+    if [ "$local_CURRENT_RELEASE_VERSION" == "" ]; then
+        echo "error: can't get current release version" >&2
+        exit $ERRNOINTERNET
+    fi
+
+    local local_CURRENT_RELEASE_VERSION_MAJOR_MINOR="$( echo $local_CURRENT_RELEASE_VERSION | sed -e 's/\.[0-9]*$//' )"
+    local local_CURRENT_RELEASE_VERSION_BUILD_NUMBR="$( echo $local_CURRENT_RELEASE_VERSION | sed -e 's/.*\.//' )"
+    local local_LOCAL_VERSION_MAJOR_MINOR="$( head -1 ${BUILD_SCRIPT_DIR}/version )"
+
+    readonly local_CURRENT_RELEASE_VERSION_STRING
+    readonly local_CURRENT_RELEASE_VERSION
+    readonly local_CURRENT_RELEASE_VERSION_MAJOR_MINOR
+    readonly local_CURRENT_RELEASE_VERSION_BUILD_NUMBR
+    readonly local_LOCAL_VERSION_MAJOR_MINOR
+
+    local local_BUILD_NUMBER=""
+    if [ $local_CURRENT_RELEASE_VERSION_MAJOR_MINOR == $local_LOCAL_VERSION_MAJOR_MINOR ]; then  #FIXME (AG): verify they've actually bumped the number
+        local_BUILD_NUMBER="$( expr $local_CURRENT_RELEASE_VERSION_BUILD_NUMBR \+ 1 )"
+    else
+        local_BUILD_NUMBER=1 # reset build number to 1
+    fi
+
+    readonly RELEASE_VERSION="$local_LOCAL_VERSION_MAJOR_MINOR.$local_BUILD_NUMBER"
+    echo "version: current => [major.minor.build:$local_CURRENT_RELEASE_VERSION] next => [major.minor.build:$RELEASE_VERSION]"
+}
+
+###############################################################################
+#
 # Synchronizes a release directory on the release server with an S3 bucket and
 # invalidates the CloudFront cache.
 #
@@ -167,8 +197,8 @@ function publish_to_s3() {
     echo ">> publishing to s3 bucket ${2}"
 
     kssh $RELEASE_SERVER_LOGIN $RELEASE_SERVER_SHELL << ENDCMDS
-        # Check to see that a version file exists in the
-        # specified version directory and is non-empty
+        # Check to see that a version file exists in the specified version directory and is
+        # non-empty.
         if [ ! -s "${INSTALLERS_DOWNLOAD_DIR}/${1}/${RELEASE_SERVER_VERSION_FILE}" ]; then
             exit $ERRS3
         fi
