Site configuration UI, remove modular deployment mode, and misc cleanup.
Among the misc cleanups:
- Rename PROD|ENTERPRISE => PUBLIC|PRIVATE
- Use flask templating for the configuration service.
- Eliminate PHP in the config service.
- Improve the "delay" configuration task.

Still TODO (in a different commit):
- Iterate on the web interface (better javascript).
- Add support for openid/ldap, etc.

Change-Id: I942f6b2eec1edbf95d629cf6b96d410c7dc855b8

diff --git a/tools/build/include/common b/tools/build/include/common
--- a/tools/build/include/common
+++ b/tools/build/include/common
@@ -128,7 +128,7 @@ readonly LABELING_FILE="$LABELING_RESOURCES_DIR/labeling-$LOWERCASE_PRODUCT.prop
 
 ###############################################################################
 #
-# Constants relating to the deploy mode (PROD/CI/STAGING/ENTERPRISE)
+# Constants relating to the deploy mode (PUBLIC|PRIVATE|CI)
 #
 ###############################################################################
 
@@ -142,7 +142,7 @@ readonly LABELING_FILE="$LABELING_RESOURCES_DIR/labeling-$LOWERCASE_PRODUCT.prop
 #
 ###############################################################################
 function is_valid_mode() {
-    if [[ "$1" != "PROD" && "$1" != "ENTERPRISE" ]]; then
+    if [[ "$1" != "PUBLIC" && "$1" != "PRIVATE" ]]; then
         return $ERRBADMODE
     fi
     return 0
@@ -151,7 +151,7 @@ function is_valid_mode() {
 # check that a valid mode was specified
 readonly MODE="${1:-}"
 if ! is_valid_mode $MODE ; then
-    echo "error: invalid build mode $MODE. Expected PROD|ENTERPRISE." >&2
+    echo "error: invalid build mode $MODE. Expected PUBLIC|PRIVATE." >&2
     exit $ERRBADMODE
 fi
 readonly LOWERCASE_MODE="$(echo $MODE | tr '[A-Z]' '[a-z]')"
@@ -162,13 +162,13 @@ readonly LOWERCASE_MODE="$(echo $MODE | tr '[A-Z]' '[a-z]')"
 #
 ###############################################################################
 
-# We use the same user account when deploying to prod/enterprise.
-# TODO (MP) use a more reasonable username. Maybe drew's changes to the build will make this better?
+# We use the same user account when deploying to public/private.
+# TODO (MP) use a more reasonable username.
 case ${LOWERCASE_MODE} in
-prod)
+public)
     readonly RELEASE_SERVER_USERNAME=release-prod
     ;;
-enterprise)
+private)
     readonly RELEASE_SERVER_USERNAME=release-prod
     ;;
 *)
@@ -196,11 +196,12 @@ readonly RELEASE_NSIS_DIR="${RELEASE_FILES_DIR}/win_installer"
 # Cloudfront/S3 constants
 #
 ###############################################################################
-if [ "$MODE" == "PROD" ]; then
+if [ "$MODE" == "PUBLIC" ]; then
     readonly RELEASE_DOMAIN="nocache.client.aerofs.com"
-elif [ "$MODE" == "ENTERPRISE" ]; then
+elif [ "$MODE" == "PRIVATE" ]; then
     # N.B. no need to create a cache/nocache variant for this since the
     # installers are packaged into openstack images anyway.
+    # TODO (MP) rename the release domain.
     readonly RELEASE_DOMAIN="nocache.client.enterprise.aerofs.com"
 fi
 readonly INSTALLER_DOWNLOAD_BUCKET="s3://${RELEASE_DOMAIN}"
@@ -233,11 +234,11 @@ function is_team_server() {
 
 ###############################################################################
 #
-# Returns 0 if the deployment mode is ENTERPRISE, 1 otherwise
+# Returns 0 if the deployment mode is PRIVATE, 1 otherwise
 #
 ###############################################################################
-function is_enterprise() {
-    if [ "$MODE" == "ENTERPRISE" ]; then
+function is_private() {
+    if [ "$MODE" == "PRIVATE" ]; then
         return 0
     fi
     return 1
@@ -245,11 +246,11 @@ function is_enterprise() {
 
 ###############################################################################
 #
-# Returns 0 if the deployment mode is PROD, 1 otherwise
+# Returns 0 if the deployment mode is PUBLIC, 1 otherwise
 #
 ###############################################################################
-function is_prod() {
-    if [ "$MODE" == "PROD" ]; then
+function is_public() {
+    if [ "$MODE" == "PUBLIC" ]; then
         return 0
     fi
     return 1
@@ -257,11 +258,11 @@ function is_prod() {
 
 ###############################################################################
 #
-# Returns 0 if the deployment mode is PROD or ENTERPRISE, 1 otherwise
+# Returns 0 if the deployment mode is PUBLIC or PRIVATE, 1 otherwise
 #
 ###############################################################################
-function is_prod_or_enterprise() {
-    if [ "$MODE" == "PROD" ] || [ "$MODE" == "ENTERPRISE" ]; then
+function is_public_or_private() {
+    if [ "$MODE" == "PUBLIC" ] || [ "$MODE" == "PRIVATE" ]; then
         return 0
     fi
     return 1
@@ -401,7 +402,7 @@ function render_template() {
 #
 # NOTE: to rollback a production release for any reason:
 #       - log into release-prod@b.arrowfs.org
-#       - s3cmd sync -P --cf-invalidate --delete-removed /data/prod-downloads/[version]/* s3://nocache.client.aerofs.com
+#       - s3cmd sync -P --cf-invalidate --delete-removed /data/public-downloads/[version]/* s3://nocache.client.aerofs.com
 #
 # @param $1 The version to publish
 # @param $2 The S3 bucket to which the release version will be pushed
@@ -417,7 +418,7 @@ function publish_to_s3() {
             exit $ERRS3
         fi
 
-        if [ "$MODE" = "PROD" ] ; then
+        if [ "$MODE" = "PUBLIC" ] ; then
             OPTS="--follow-symlinks --acl-public --delete-removed --cf-invalidate"
         else
             OPTS="--follow-symlinks --acl-public --delete-removed"
diff --git a/tools/populate/populate b/tools/populate/populate
--- a/tools/populate/populate
+++ b/tools/populate/populate
@@ -9,7 +9,7 @@ readonly ERRBADPRODUCT=3
 function print_usage() {
     echo "usage: $0 [mode] [product] [os] [resource_root_dir] [output_dir]" >&2
     echo "    [mode]              Specifies which mode the properties are for" >&2
-    echo "                        Can be PROD|CI|ENTERPRISE." >&2
+    echo "                        Can be PUBLIC|PRIVATE|CI." >&2
     echo "    [product]           Specifies which product the properties are for" >&2
     echo "                        Can be TEAM_SERVER|CLIENT." >&2
     echo "    [os]                OS to populate for. Can be osx, win, linux/i386 or" >&2
@@ -72,21 +72,21 @@ function copy_os_specific_resources() {
 # This keeps aerofs from being updated
 # This version number must be kept in sync with src/launcher/launcher.lib/liblauncher.cpp
 function create_max_version_file() {
-    if [[ "$MODE" == 'CI' || "$MODE" == 'ENTERPRISE' ]]
+    if [[ "$MODE" == 'CI' || "$MODE" == 'PRIVATE' ]]
     then
         echo "100.0.0" > "$APPROOT"/version
     fi
 }
 
 function create_site_properties_file() {
-    if [[ "$MODE" == 'ENTERPRISE' ]]
+    if [[ "$MODE" == 'PRIVATE' ]]
     then
         set +e
-        wget -qO- --no-check-certificate -T 5 https://persistent.syncfs.com:5435/ > "$APPROOT"/site-config.properties
+        wget -qO- --no-check-certificate -T 5 https://unified.syncfs.com:5435/ > "$APPROOT"/site-config.properties
 
         if [[ $? -ne 0 ]]
         then
-            echo "ERROR: Local prod configuration service not available."
+            echo "ERROR: Configuration service not available."
             exit 1
         fi
 
diff --git a/tools/vm-tool b/tools/vm-tool
--- a/tools/vm-tool
+++ b/tools/vm-tool
@@ -1,13 +1,7 @@
-#!/bin/bash -ue
+#!/bin/bash
+set -eu
 
 readonly AEROFS_ROOT=$(cd "${BASH_SOURCE[0]%/*}"/.. && pwd )
-
-#
-# Local Production Aliases.
-#
-# In this file, vm is short for virtual machine prodcution. Aliases that
-# are meant to be used publicly are prefixed with "vm-".
-#
 
 #
 # Execute a command in a specified directory changes back to the original
@@ -50,87 +44,15 @@ function _uppercase_repo()
     whoami | tr [a-z] [A-Z]
 }
 
-function _print-available-boxes()
-{
-    _check-mode
-
-    case ${MODE} in
-        unified)
-            echo "available box: unified" >&2
-            ;;
-        modular)
-            echo "available boxes: persistent, transient" >&2
-            ;;
-    esac
-
-}
-
-function _print-available-deployment-modes()
-{
-    echo "available deployment_modes: modular, unified" >&2
-}
-
-function _check-mode()
-{
-    bad_mode=false
-
-    case ${MODE} in
-        unified) ;;
-        modular) ;;
-        *) bad_mode=true ;;
-    esac
-
-    if [ "$bad_mode" = "true" ]
-    then
-        echo "unrecognized mode:$MODE}" >&2
-        _print-available-deployment-modes
-        exit 1
-    fi
-}
-
-function _check-box()
-{
-    local box=''
-
-    if [ "$MODE" = "modular" ]
-    then
-        case ${1:-} in
-            persistent) box=persistent ;;
-            transient ) box=transient ;;
-        esac
-    fi
-
-    if [ "$MODE" = "unified" ]
-    then
-        case ${1:-} in
-            unified ) box=unified ;;
-        esac
-    fi
-
-    if [[ -z "$box" ]]; then
-        echo "unrecognized box:${1:-}" >&2
-        _print-available-boxes
-        exit 1
-    fi
-
-    echo $box
-}
-
 #
-# Runs a command in the local-prod directory
+# Runs a command in the development directory
 #
 function _local-prod-cmd()
 {
-    if [ $# -eq 0 ]
-    then
-        echo "usage: _local-prod-cmd executable [args]"
-        exit 1
-    fi
-
     local command=$1
     shift
 
-    do_in $AEROFS_ROOT/packaging/bakery/development/mode/"$MODE" ../../$command "$@"
+    do_in $AEROFS_ROOT/packaging/bakery/development ./$command "${@:-}"
 }
 
 # -----------------------------------------------------------
@@ -151,7 +73,7 @@ function _package()
 
     local package=$(echo $1 | sed 's/-/_/g')
     do_in $AEROFS_ROOT ant package_${package} \
-        -Dmode=ENTERPRISE \
+        -Dmode=PRIVATE \
         -Dproduct=CLIENT \
         -Drepo="$repo"
     do_in $AEROFS_ROOT/packaging make packagelist
@@ -166,7 +88,7 @@ function _package-and-upload-versions()
 
     do_in $AEROFS_ROOT ant clean package_servers upload_versions \
         -Dproduct=CLIENT \
-        -Dmode=ENTERPRISE \
+        -Dmode=PRIVATE \
         -Drepo="$repo"
     do_in $AEROFS_ROOT/packaging make packagelist
 }
@@ -177,73 +99,25 @@ function _package-and-upload-versions()
 
 function _vm-deploy()
 {
-    if [[ $# -ne 2 ]]; then
-        echo "usage: vm-tool deploy box_name package_name" >&2
-        _print-available-boxes
-        exit 1
-    fi
-
-    # IMPORTANT: you must do this in two parts because otherwise
-    # the exit status of the subshell will not be preseved; i.e.
-    # local box=$(...) will break, but the two-parter below wont
-    local box=''
-    box=$(_check-box $1)
-
-    local package=$2
-
+    local package=$1
     _package $package
-    _local-prod-cmd vm-ctrl "$MODE" deploy $box $package
-}
 
-function _vm-deploy-all()
-{
-    if [[ $# -ne 1 ]] || [[ -z "${1}" ]]; then
-        echo "usage: vm-tool deploy-all box_name" >&2
-        _print-available-boxes
-        exit 1
-    fi
-
-    local box=''
-    box=$(_check-box $1)
-
-    #_package-and-upload-versions
-    _vm-kick $box
+    _local-prod-cmd vm-ctrl deploy $package
 }
 
 # -----------------------------------------------------------
 # Kicks
 # -----------------------------------------------------------
 
-function _print-kick-usage()
-{
-    echo "usage: vm-tool kick [box_name]" >&2
-    echo "available boxes: persistent, transient" >&2
-}
-
 function _vm-kick()
 {
-    if [[ $# -ne 1 ]] || [[ -z "$1" ]]; then
-        echo "usage: vm-tool kick [box_name]" >&2
-        _print-available-boxes
-        exit 1
-    fi
-
-    local box=''
-    box=$(_check-box $1)
-
     _package-and-upload-versions
-    _local-prod-cmd vm-ctrl "$MODE" kick ${box}
+    _local-prod-cmd vm-ctrl kick
 }
 
 # -----------------------------------------------------------
 # Virtual Machines
 # -----------------------------------------------------------
-
-function _print-create-usage()
-{
-    echo "usage: vm-tool create deployment_mode [bridge_interface]" >&2
-    _print-available-deployment-modes
-}
 
 function _vm-create()
 {
@@ -251,89 +125,122 @@ function _vm-create()
     repo=$(_lowercase_repo)
 
     _package-and-upload-versions
-    _local-prod-cmd vm-make "$repo" "$MODE" "${@}"
-}
-
-function _print-start-usage()
-{
-    echo "usage: vm-tool start deployment_mode [bridge_interface]" >&2
-    _print-available-deployment-modes
+    _local-prod-cmd vm-make "$repo" ${@:-}
 }
 
 function _vm-start()
 {
-    _local-prod-cmd vm-ctrl "$MODE" start "${@}"
+    _local-prod-cmd vm-ctrl start "${@:-}"
 }
 
 function _vm-halt()
 {
-    _local-prod-cmd vm-ctrl "$MODE" halt "${@:-}"
+    _local-prod-cmd vm-ctrl halt
 }
 
 function _vm-kill()
 {
-    _local-prod-cmd vm-ctrl "$MODE" kill "${@:-}"
+    _local-prod-cmd vm-ctrl kill
 }
 
 # -----------------------------------------------------------
 # SSH
 # -----------------------------------------------------------
 
-function _print-ssh-usage()
-{
-    echo "usage: vm-tool ssh box_name" >&2
-    _print-available-boxes
-    echo "simply sudo su to get root access (no password required)." >&2
-}
-
 function _vm-ssh()
 {
-    if [[ $# -ne 1 ]] || [[ -z "${1}" ]]; then
-        _print-ssh-usage
-        exit 1
-    fi
-
-    local box=''
-    box=$(_check-box $1)
-
-    do_in $AEROFS_ROOT/packaging/bakery/development/mode/"$MODE" vagrant ssh $box
+    do_in $AEROFS_ROOT/packaging/bakery/development vagrant ssh
 }
 
 # -----------------------------------------------------------
-# main
+# Main
 # -----------------------------------------------------------
+
+function usage()
+{
+    echo "Usage: $0 <command> [<command_argument>]" >&2
+    echo >&2
+    echo "Available commands:" >&2
+    echo >&2
+    echo "    create [<bridge_interface>]" >&2
+    echo "    start  [<bridge_interface>]" >&2
+    echo "    ssh" >&2
+    echo "    halt" >&2
+    echo "    kill" >&2
+    echo "    kick" >&2
+    echo "    deploy <package_name>" >&2
+
+    exit 1
+}
+
+function check_no_args()
+{
+    if [ $# -ne 0 ]
+    then
+        echo "Error: command does not accept an argument." >&2
+        echo >&2
+        usage
+    fi
+}
+
+function check_zero_or_one_args()
+{
+    if [ $# -ne 0 ] && [ $# -ne 1 ]
+    then
+        usage
+    fi
+}
 
 function main()
 {
-    if [[ $# -lt 2 ]]; then
-        echo "usage: $0 deployment_mode ( create | start | halt | kill | deploy | ssh ) [command_arguments]" >&2
+    if [ $# -eq 0 ] || [ $# -gt 2 ]
+    then
+        echo "Error: invalid number of parameters provided." >&2
         echo >&2
-        echo "special cases:" >&2
-        echo "      create [bridge_interface]" >&2
-        echo "      start  [bridge_interface]" >&2
-        echo "      ssh    [box_name]" >&2
-        echo >&2
-        _print-available-deployment-modes
-        exit 1
+        usage
     fi
 
-    readonly MODE=$1
-    shift
     local command=$1
     shift
 
     case $command in
-        "create"    ) _vm-create     "${@:-}" ;;
-        "start"     ) _vm-start      "${@:-}" ;;
-        "halt"      ) _vm-halt       "${@:-}" ;;
-        "kill"      ) _vm-kill       "${@:-}" ;;
-        "deploy"    ) _vm-deploy     "${@:-}" ;;
-        "deploy-all") _vm-deploy-all "${@:-}" ;;
-        "ssh"       ) _vm-ssh        "${@:-}" ;;
-        "kick"      ) _vm-kick       "${@:-}" ;;
-        *           )
-            echo "unrecognized command $command" >&2
-            exit 2
+        "create")
+            check_zero_or_one_args ${@:-}
+            _vm-create ${1:-}
+            ;;
+        "start")
+            check_zero_or_one_args ${@:-}
+            _vm-start ${1:-}
+            ;;
+        "halt")
+            check_no_args ${@:-}
+            _vm-halt
+            ;;
+        "kill")
+            check_no_args ${@:-}
+            _vm-kill
+            ;;
+        "kick")
+            check_no_args ${@:-}
+            _vm-kick
+            ;;
+        "deploy")
+            if [ $# -ne 1 ]
+            then
+                echo "Error: deploy requires a package name argument." >&2
+                echo >&2
+                usage
+            fi
+            _vm-deploy $1
+            ;;
+        "ssh")
+            check_no_args ${@:-}
+            _vm-ssh
+            ;;
+        *)
+            echo "Error: invalid command name \"$command\"." >&2
+            echo >&2
+            usage
             ;;
     esac
 }
