ENG-4099 get-defects handles broken zip files.
Use `jar xvf` over `unzip`. Display a warning when the zip file might be
busted.

Change-Id: If278ed5f3c8b6f2ae836065d652eca43cf17c5ad

diff --git a/tools/get-defects b/tools/get-defects
--- a/tools/get-defects
+++ b/tools/get-defects
@@ -1,5 +1,7 @@
 #!/bin/bash
-# This script retrives defect log files.
+#
+# This script retrieves defect log files.
+
 set -eu
 
 if [ $# -eq 0 ]; then
@@ -14,46 +16,37 @@ BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 main()
 {
-    for DEFECT in $DEFECTS; do
-        TARGET_FOLDER="defect-$DEFECT" # puts this into the pwd
-        if [[ -e "$TARGET_FOLDER" ]]; then
+    for DEFECT in "$DEFECTS"
+    do
+        TARGET_FOLDER="$(pwd)"/"defect-$DEFECT"
+        if [[ -e "$TARGET_FOLDER" ]]
+        then
             echo "$TARGET_FOLDER already exists."
             continue
         fi
 
-        scp -r dryad.aerofs.com:/data/defects/$DEFECT $TARGET_FOLDER
+        echo "Copying logs for $DEFECT"
+        scp -r dryad.aerofs.com:/data/defects/"$DEFECT" "$TARGET_FOLDER"
 
         for file in "$TARGET_FOLDER"/*.zip
         do
-            echo $file
-            typeset destdir=${file%%.zip}
-            mkdir -p $destdir ||:
-            unzip -o "$file" -d "$destdir"
-            rm $file
-
-            echo "Extracting logs for $DEFECT"
-
-            if [ ! -z "$(ls $destdir/name*map 2>/dev/null)" ]
+            echo "Extracting logs from $file"
+            typeset destdir="${file%%.zip}"
+            mkdir -p "$destdir" ||:
+            pushd "$destdir" 1>/dev/null
+            set +e
+            jar xvf "$file"
+            if [ $? -ne 0 ]
             then
-                echo "Reverse crc logs for $DEFECT"
-
-                for i in daemon cli gui; do
-                    if [ -f "$destdir/$i.log" ]; then
-                        mv "$destdir/$i.log" "$destdir/unmapped.$i.log"
-
-                        cat "$destdir/unmapped.$i.log" | \
-                            ${BASE}/reverse-crc/reverse-crc.py -f $(ls "$destdir/name"*"map") > \
-                            "$destdir/$i.log"
-                    fi
-                done
+                echo "WARNING: Your zip file might be corrupt. Some logs might be missing."
             fi
-
-            rm -f "$destdir/unmapped"*
-            rm -f "$destdir/name"*"map"
+            set -e
+            popd 1>/dev/null
+            rm "$file"
         done
     done
 
-    echo "Done"
+    echo "Logs have been fetched. Script will exit."
 }
 
 main
